//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_TP2_52D_14_1920i
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyReg
    {
        public string isin { get; set; }
        public Nullable<decimal> minval { get; set; }
        public Nullable<decimal> openingval { get; set; }
        public Nullable<decimal> maxval { get; set; }
        public Nullable<decimal> closingval { get; set; }
        public System.DateTime dailydate { get; set; }
    
        public virtual Instrument Instrument { get; set; }
    }
}
