//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_TP2_52D_14_1920i
{
    using System;
    using System.Collections.Generic;
    
    public partial class INSTRUMENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INSTRUMENT()
        {
            this.DAILYREG = new HashSet<DAILYREG>();
            this.POSITION = new HashSet<POSITION>();
        }
    
        public string isin { get; set; }
        public string description { get; set; }
        public Nullable<int> mrktcode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DAILYREG> DAILYREG { get; set; }
        public virtual MARKET MARKET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POSITION> POSITION { get; set; }
    }
}
