//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_TP2_52D_14_1920i
{
    using System;
    using System.Collections.Generic;
    
    public partial class Portfolio_Summary
    {
        public string name { get; set; }
        public Nullable<int> NoInstruments { get; set; }
        public Nullable<decimal> totalval { get; set; }
    }
}
